#!/usr/bin/env php
<?php
// application.php

require __DIR__ . '/vendor/autoload.php';

use Antipodes\Wordpress\SwitchComments\SwitchCommentsCommand;
use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new SwitchCommentsCommand());

$application->run();